-- MySQL Script generated by MySQL Workbench
-- Mon Sep 29 16:06:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema seguridad_plazas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema seguridad_plazas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seguridad_plazas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `seguridad_plazas` ;

-- -----------------------------------------------------
-- Table `seguridad_plazas`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`tipo_usuarios` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(12) NOT NULL,
  `nombre_usuario` VARCHAR(50) NULL DEFAULT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `id_rol` INT NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `rut` (`rut` ASC) VISIBLE,
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `seguridad_plazas`.`tipo_usuarios` (`id_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`plazas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`plazas` (
  `id_plaza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_plaza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`reportes` (
  `id_reporte` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Sospechoso', 'Accidente', 'Objeto Peligroso', 'Comportamiento Raro') NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_plaza` INT NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_reporte`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_plaza` (`id_plaza` ASC) VISIBLE,
  CONSTRAINT `reportes_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `seguridad_plazas`.`usuarios` (`id_usuario`),
  CONSTRAINT `reportes_ibfk_2`
    FOREIGN KEY (`id_plaza`)
    REFERENCES `seguridad_plazas`.`plazas` (`id_plaza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`archivos_reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`archivos_reporte` (
  `id_archivo` INT NOT NULL AUTO_INCREMENT,
  `ruta_archivo` VARCHAR(255) NOT NULL,
  `id_reporte` INT NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_archivo`),
  INDEX `id_reporte` (`id_reporte` ASC) VISIBLE,
  CONSTRAINT `archivos_reporte_ibfk_1`
    FOREIGN KEY (`id_reporte`)
    REFERENCES `seguridad_plazas`.`reportes` (`id_reporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`camaras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`camaras` (
  `id_camara` INT NOT NULL AUTO_INCREMENT,
  `ubicacion` VARCHAR(100) NOT NULL,
  `estado` ENUM('ACTIVA', 'INACTIVA') NULL DEFAULT 'ACTIVA',
  `id_plaza` INT NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_camara`),
  INDEX `id_plaza` (`id_plaza` ASC) VISIBLE,
  CONSTRAINT `camaras_ibfk_1`
    FOREIGN KEY (`id_plaza`)
    REFERENCES `seguridad_plazas`.`plazas` (`id_plaza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `seguridad_plazas`.`juntas_vecinos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seguridad_plazas`.`juntas_vecinos` (
  `id_junta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `id_plaza` INT NOT NULL,
  `created_by` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_junta`),
  INDEX `id_plaza` (`id_plaza` ASC) VISIBLE,
  CONSTRAINT `juntas_vecinos_ibfk_1`
    FOREIGN KEY (`id_plaza`)
    REFERENCES `seguridad_plazas`.`plazas` (`id_plaza`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


