-- MySQL Script generated by MySQL Workbench
-- Thu May 15 10:24:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_ventas_4e
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_ventas_4e
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_ventas_4c` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_ventas_4c` ;

-- -----------------------------------------------------
-- Table `sistema_ventas_4e`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_ventas_4c`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(70) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `precio` FLOAT NOT NULL,
  `stock` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_ventas_4e`.`tipo_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_ventas_4c`.`tipo_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(50) NOT NULL,
  `descripcion_tipo` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_ventas_4e`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_ventas_4c`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_usuario_id` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `updated_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `sistema_ventas_4c`.`tipo_usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_ventas_4e`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_ventas_4c`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NULL DEFAULT NULL,
  `fecha_venta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `update_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_ventas` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_ventas`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_ventas_4c`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_ventas_4e`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_ventas_4c`.`detalle_ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `venta_id` INT NULL DEFAULT NULL,
  `producto_id` INT NULL DEFAULT NULL,
  `descripcion_detalle` VARCHAR(200) NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` FLOAT NOT NULL DEFAULT '0',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `update_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL DEFAULT NULL,
  `update_by` INT NULL DEFAULT NULL,
  `deleted` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_detalle_ventas` (`venta_id` ASC) VISIBLE,
  INDEX `fk_productos_detalle_ventas` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_detalle_ventas`
    FOREIGN KEY (`producto_id`)
    REFERENCES `sistema_ventas_4c`.`productos` (`id`),
  CONSTRAINT `fk_ventas_detalle_ventas`
    FOREIGN KEY (`venta_id`)
    REFERENCES `sistema_ventas_4c`.`ventas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tipo_usuarios (nombre_tipo, descripcion_tipo, created_by, updated_by)
VALUES ('Administrador', 'Accede a todas las funciones del sistema, incluida la administración de usuarios.', 1, 1  ),
('Vendedor','Interactua con los clientes para vender productos de la empresa.', 1, 1  );

INSERT INTO usuarios (nombre_tipo, contraseña, correo, tipo_usuario_id, created_by, updated_by)
VALUES ('sistema','$2y$10$2pEjT0G2k9YzHs1oZ.abcde3Y8GkmHfvhO1/abcxyz','sistema@plataforma.cl',NULL, NULL, NULL),
('javier.mendez', '$&234567', 'javiermendez@gmail.com', 1, 1, 1),
('maxi.reyes', '$#$#%%&&84745548', 'maxireyes@gmail.com', 2, 1, 1),
('benja.gajardo', '$#$56778676445', 'benjagajardo@gmail.com', 2, 1, 1);


INSERT INTO productos (nombre_producto, descripcion, precio, stock, created_by, updated_by)
VALUES ('Zapatillas', 'Diferentes tipos de zapatilas para todo uso', '40.000', '200', 1, 1),
('Poleras', 'Poleras de todo tipo de diferentes calidades y materiales', '20.000', '400', 1, 1),
('Pantalones', 'Pantalones de buen material y tipos, jeans baggy, slim, skinny, ect...', '60.000', '550', 1, 1 );

INSERT INTO ventas (usuario_id, fecha_venta, created_by, update_by)
VALUES 
(2, '2025-07-24', 1, 1),
(2, '2025-05-29', 1, 1),
(2, '2025-08-19', 1, 1),
(2, '2025-02-10', 1, 1);

INSERT INTO detalle_ventas (
    venta_id, producto_id, descripcion_detalle, cantidad, precio_unitario, created_by, update_by)
VALUES ('1', '2', 'Zapatillas air jordan 4 x off white talla 44', '1', '40.000', 1, 1 ),
('2', '2', 'Poleras nike deportivas talla M', '2', '40.000', 1, 1),
('3', '2', 'Poleras adidas colo colo originals talla XL', '3', '60.000', 1, 1),
('4', '2', 'Pantalon true religion', '2', '120.000', 1, 1);








